### PR TITLE
Debianized Greenzie Noetic Fork

### PR DESCRIPTION
**Pull request by kakaday22**
Adding debianization changes to branch

### CODE REVIEW

**Comment by kakaday22** [comment]
@AGummyBear these are my changes to debianize the projects `phidgets_api` and `phidgets_high_speed_encoders`  once merge, we could rename your branch `noetic`  what do you think?

**Review by AGummyBear — COMMENTED** [review]
I'm far from an expert in debianization, so I'm going to have to trust you that this works and produces functional debs.

A couple things that jump out at me:/
- Naming: We are going from `1.0.4-0focal` to `1.0.4-0-greenzie-focal1`. Is that a convention that we're following? I'm not sure the rules that are used when deciding what is a newer version.
- We're going to be mixing debs that we made, with those made available by the original package. This should be fine, as long as we built against the same code that was used for the public debs (I think we did). But it could be a maintainability headache in the future. The alternative is that we use entirely our versions, and debianize all of their packages (which is a big pain now). I think we just need to be careful that we don't update the versions on our package server to something newer without updating the ones built locally, which could introduce compatibility issues.

**Comment by kakaday22** [comment]
From what I am seen in melodic, when we debianize we only increase the version by 100 to prevent apt to install a different version. This logic can lead to a bit chaos

for Noetic let's start standardizing and using debian/control properly, that means:
* locking packages to certain version or range of versions  to prevent the packages to randomly update and break (if any)
* For forked packages, like this one. I want to move to just keep the original upstream version suffix with "greenzie" at the end, that way for maintainability, if we move to a different ros distro, I can easily identify which packages were forked by us and which versions were taken from

I struggled a little trying to find and understand which packages were forked when compiling the list

**Comment by kakaday22** [comment]
for instance, this is currently in `greenzie-experimental focal main`
image

Notice that there were suffixed with `greenzie` and now we know these are forked versions of the packages

**Comment by AGummyBear** [comment]
Alright, awesome!

**Review by AGummyBear — APPROVED** [review]

**Pull request merged**
